#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sentry-sdk
Version  : 1.5.1
Release  : 2
URL      : https://files.pythonhosted.org/packages/9a/43/c0c807dadf38d0eb7c18ed66b7d14d33d679750f928ca4c6d1f5626182f2/sentry-sdk-1.5.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/9a/43/c0c807dadf38d0eb7c18ed66b7d14d33d679750f928ca4c6d1f5626182f2/sentry-sdk-1.5.1.tar.gz
Summary  : Python client for Sentry (https://sentry.io)
Group    : Development/Tools
License  : BSD-3-Clause
Requires: sentry-sdk-license = %{version}-%{release}
Requires: sentry-sdk-python = %{version}-%{release}
Requires: sentry-sdk-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(certifi)
BuildRequires : pypi(urllib3)

%description
<p align="center">
<a href="https://sentry.io" target="_blank" align="center">
<img src="https://sentry-brand.storage.googleapis.com/sentry-logo-black.png" width="280">
</a>
</p>

%package license
Summary: license components for the sentry-sdk package.
Group: Default

%description license
license components for the sentry-sdk package.


%package python
Summary: python components for the sentry-sdk package.
Group: Default
Requires: sentry-sdk-python3 = %{version}-%{release}

%description python
python components for the sentry-sdk package.


%package python3
Summary: python3 components for the sentry-sdk package.
Group: Default
Requires: python3-core
Provides: pypi(sentry_sdk)
Requires: pypi(certifi)
Requires: pypi(urllib3)

%description python3
python3 components for the sentry-sdk package.


%prep
%setup -q -n sentry-sdk-1.5.1
cd %{_builddir}/sentry-sdk-1.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639425682
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sentry-sdk
cp %{_builddir}/sentry-sdk-1.5.1/LICENSE %{buildroot}/usr/share/package-licenses/sentry-sdk/3e100b2f32e3b106d00353c68b24a2e3c70adf79
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sentry-sdk/3e100b2f32e3b106d00353c68b24a2e3c70adf79

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
